name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-image]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i k8s/deployment.yaml
    
    - name: Update Image Version in the yaml
      uses: fjogeleit/yaml-update-action@main
      with:
          valueFile: 'k8s/deployment.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: '${{ github.event.client_payload.image }}'
          masterBranchName: 'main'
          branch: 'main'
          message: 'Update Image Version to ${{ github.event.client_payload.image }}' 
    


